<?php

namespace Database\Seeders;

use App\Models\ProgramContent;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProgramContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $contents = [
            // ==================== BERANDA / LANDING HOME (/) ====================
            [
                'section' => 'home_hero',
                'key' => 'eyebrow',
                'title' => 'Program Penelitian Remaja',
                'body' => null,
                'icon' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'home_hero',
                'key' => 'title',
                'title' => 'Suara Remaja untuk <span class="accent">Keterlibatan Ayah</span> yang Lebih Bermakna',
                'body' => null,
                'icon' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'home_hero',
                'key' => 'subtitle',
                'title' => null,
                'body' => 'STEP adalah ruang aman bagi remaja untuk mengekspresikan harapan, cerita, dan aspirasi mengenai peran ayah. Identitasmu terjaga sepenuhnya.',
                'icon' => null,
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'section' => 'home_hero',
                'key' => 'button_text',
                'title' => 'Buka Ruang Ekspresi',
                'body' => null,
                'icon' => null,
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'section' => 'home_hero_stats',
                'key' => 'stat_1',
                'title' => '100%',
                'body' => 'Anonim & Aman',
                'icon' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'home_hero_stats',
                'key' => 'stat_2',
                'title' => 'Gratis',
                'body' => 'Tanpa Biaya',
                'icon' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'home_hero_stats',
                'key' => 'stat_3',
                'title' => 'Real',
                'body' => 'Riset Nyata',
                'icon' => null,
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'section' => 'home_hero_cards',
                'key' => 'card_1',
                'title' => 'Aman & Anonim',
                'body' => 'Ekspresikan perasaanmu tanpa khawatir. Identitasmu tetap sepenuhnya terjaga.',
                'icon' => '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#b2dfdb" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'home_hero_cards',
                'key' => 'card_2',
                'title' => 'Media Aspirasi',
                'body' => 'Sampaikan harapan dan saranmu mengenai peran ayah dalam hidupmu.',
                'icon' => '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#fbbf24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'home_hero_cards',
                'key' => 'card_3',
                'title' => 'Kontribusi Nyata',
                'body' => 'Data yang terkumpul menjadi basis penelitian untuk generasi yang lebih baik.',
                'icon' => '<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="#7ec8e3" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'section' => 'home_features_header',
                'key' => 'header',
                'title' => 'Membangun Jembatan antara Remaja dan Ayah',
                'body' => 'Kehadiran ayah terbukti berpengaruh besar pada perkembangan mental dan emosional remaja. Mari kita suarakan bersama.',
                'icon' => 'Mengapa STEP Penting?',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'home_bento_cards',
                'key' => 'bento_1',
                'title' => 'Edukasi Peran Ayah',
                'body' => 'Memberikan pemahaman mendalam tentang betapa krusialnya kehadiran ayah bagi perkembangan mental dan emosional remaja. Keterlibatan aktif ayah menciptakan fondasi kepercayaan diri yang kuat sejak dini.',
                'icon' => '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></svg>',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'home_bento_cards',
                'key' => 'bento_2',
                'title' => 'Kesehatan Mental',
                'body' => 'Membantu remaja mengidentifikasi perasaan dan memberikan ruang aman untuk bercerita tanpa penilaian.',
                'icon' => '<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'home_bento_cards',
                'key' => 'bento_3',
                'title' => 'Pencegahan Dini',
                'body' => 'Mengidentifikasi sejak dini tanda-tanda <em>fatherless</em> dan dampaknya bagi perilaku remaja di lingkungan sosial.',
                'icon' => '<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'section' => 'home_bento_cards',
                'key' => 'bento_4',
                'title' => '72%',
                'body' => 'Remaja Inginkan Ayah Lebih Hadir. Data awal menunjukkan mayoritas remaja berharap ayah lebih aktif terlibat dalam kehidupan sehari-hari mereka.',
                'icon' => null,
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'section' => 'home_bento_cards',
                'key' => 'bento_5',
                'title' => 'Keterlibatan Aktif',
                'body' => 'Mendorong ayah terlibat lebih aktif dalam kegiatan sehari-hari dan pengambilan keputusan penting bagi remaja.',
                'icon' => '<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'section' => 'home_cta',
                'key' => 'cta',
                'title' => 'Suaramu Berarti.<br>Masa Depan Dimulai dari Sini.',
                'body' => 'Tidak butuh waktu lama. Cukup beberapa menit untuk berbagi pengalamanmu dan membantu riset yang bermakna.',
                'icon' => 'Bergabung Sekarang',
                'sort_order' => 1,
                'is_active' => true,
            ],

            // ==================== TENTANG (/tentang) ====================
            [
                'section' => 'about_hero',
                'key' => 'hero',
                'title' => 'Tentang Program STEP',
                'body' => 'Mengenal lebih dekat visi dan misi kami untuk remaja dan keluarga.',
                'icon' => 'Tentang STEP',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'about_content',
                'key' => 'background',
                'title' => 'Latar Belakang',
                'body' => '<p>Program STEP (Studying Teens\' Expectations on Paternal Involvement) lahir dari keprihatinan terhadap fenomena <i>fatherless</i> di Indonesia. Banyak remaja merasa kehilangan arah atau kurang mendapatkan dukungan emosional dari sosok ayah.</p><p>Penelitian ini bertujuan untuk memetakan apa yang sebenarnya diharapkan oleh para remaja dari ayah mereka, sehingga dapat menjadi masukan berharga bagi para orang tua dan pendidik.</p>',
                'icon' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'about_content',
                'key' => 'vision',
                'title' => 'Visi Kami',
                'body' => '<p>Menciptakan generasi remaja yang tangguh secara emosional melalui penguatan peran ayah dalam pengasuhan.</p>',
                'icon' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'about_missions',
                'key' => 'mission_1',
                'title' => 'Misi 1',
                'body' => 'Menjadi wadah aspirasi remaja yang aman dan tersembunyi.',
                'icon' => '1',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'about_missions',
                'key' => 'mission_2',
                'title' => 'Misi 2',
                'body' => 'Mengumpulkan data empiris untuk penelitian OPSI 2026.',
                'icon' => '2',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'about_missions',
                'key' => 'mission_3',
                'title' => 'Misi 3',
                'body' => 'Memberikan edukasi kepada pihak sekolah dan orang tua.',
                'icon' => '3',
                'sort_order' => 3,
                'is_active' => true,
            ],

            // ==================== EDUKASI (/edukasi) ====================
            [
                'section' => 'education_hero',
                'key' => 'hero',
                'title' => 'Edukasi Program STEP',
                'body' => 'Memahami pentingnya keterlibatan ayah bagi masa depan remaja.',
                'icon' => 'Edukasi STEP',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'education_cards',
                'key' => 'card_1',
                'title' => 'Apa itu Keterlibatan Ayah?',
                'body' => 'Bukan sekadar mencari nafkah, tapi kehadiran secara emosional, mendidik, dan menjadi teman diskusi bagi remaja.',
                'icon' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'education_cards',
                'key' => 'card_2',
                'title' => 'Dampak Positif',
                'body' => 'Remaja dengan ayah yang terlibat cenderung memiliki prestasi akademik lebih baik dan regulasi emosi yang stabil.',
                'icon' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'education_cards',
                'key' => 'card_3',
                'title' => 'Tips Komunikasi',
                'body' => 'Mulailah dengan hal-hal kecil, sampaikan perasaanmu secara jujur, dan mintalah waktu luang kepada ayah untuk sekadar mengobrol.',
                'icon' => null,
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'section' => 'education_footer',
                'key' => 'footer',
                'title' => 'Ingin tahu lebih banyak?',
                'body' => 'Kami menyediakan berbagai materi literasi terkait pola asuh ayah yang bisa kamu pelajari lebih lanjut.',
                'icon' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],

            // ==================== PENCEGAHAN (/pencegahan) ====================
            [
                'section' => 'prevention_hero',
                'key' => 'hero',
                'title' => 'Pencegahan Dampak <i>Fatherless</i>',
                'body' => 'Langkah-langkah strategis untuk menjaga kesehatan mental remaja.',
                'icon' => 'Pencegahan STEP',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'prevention_main',
                'key' => 'intro',
                'title' => 'Mengapa Perlu Pencegahan?',
                'body' => 'Fenomena lack of fathering atau absennya peran ayah dapat memicu masalah perilaku, rendahnya kepercayaan diri, hingga depresi pada remaja. STEP hadir untuk membantu mengidentifikasi risiko ini lebih dini.',
                'icon' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'prevention_steps',
                'key' => 'step_1',
                'title' => 'Peningkatan Literasi Pengasuhan',
                'body' => null,
                'icon' => '1',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'prevention_steps',
                'key' => 'step_2',
                'title' => 'Ruang Aman <i>Curhat</i> Anonim',
                'body' => null,
                'icon' => '2',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'prevention_steps',
                'key' => 'step_3',
                'title' => 'Koneksi dengan Guru BK/Konselor',
                'body' => null,
                'icon' => '3',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'section' => 'prevention_cards',
                'key' => 'card_1',
                'title' => 'Self-Awareness',
                'body' => 'Mengenali tanda-tanda stres atau kesedihan akibat kurangnya perhatian orang tua.',
                'icon' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'prevention_cards',
                'key' => 'card_2',
                'title' => 'Positive Coping',
                'body' => 'Menyalurkan emosi melalui kegiatan positif seperti olahraga atau menulis di STEP.',
                'icon' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'prevention_cards',
                'key' => 'card_3',
                'title' => 'Healthy Circle',
                'body' => 'Membangun pertemanan yang mendukung dan saling menguatkan.',
                'icon' => null,
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'section' => 'prevention_cards',
                'key' => 'card_4',
                'title' => 'Openness',
                'body' => 'Keberanian untuk mengungkapkan harapan kepada ayah secara langsung atau melalui media.',
                'icon' => null,
                'sort_order' => 4,
                'is_active' => true,
            ],
        ];

        foreach ($contents as $content) {
            ProgramContent::updateOrCreate(
                ['section' => $content['section'], 'key' => $content['key']],
                $content
            );
        }
    }
}
