<?php
// Variables
return [
  "creatorName" => "STEP - Paternal Involvement",
  "creatorUrl" => "https://step-opsi.id",
  "templateName" => "STEP",
  "templateSuffix" => "Paternal Involvement",
  "templateVersion" => "1.0.0",
  "templateFree" => true,
  "templateDescription" => "STEP adalah platform edukasi dan dukungan untuk membangun peran aktif ayah dalam tumbuh kembang anak yang optimal.",
  "templateKeyword" => "paternal involvement, keterlibatan ayah, edukasi ayah, tumbuh kembang anak, STEP",
  "licenseUrl" => "https://themeforest.net/licenses/standard",
  "livePreview" => "https://demos.pixinvent.com/vuexy-html-laravel-admin-template/demo-1/",
  "productPage" => "https://themeforest.net/item/vuexy-vuejs-html-laravel-admin-dashboard-template/23328599",
  "support" => "https://pixinvent.ticksy.com/",
  "moreThemes" => "https://themeforest.net/user/pixinvent/portfolio",
  "ogTitle" => "STEP - Paternal Involvement | Platform Edukasi Keterlibatan Ayah",
  "ogImage" => "https://step-opsi.id/assets/img/illustrations/bg-shape-image-light.png",
  "ogType" => "website",
  "documentation" => "https://demos.pixinvent.com/vuexy-html-admin-template/documentation",
  "generator" => "",
  "changelog" => "https://demos.pixinvent.com/vuexy/changelog.html",
  "repository" => "https://github.com/pixinvent/vuexy-html-laravel-admin-template",
  "gitRepo" => "vuexy-html-laravel-admin-template",
  "gitRepoAccess" => "https://tools.pixinvent.com/github/github-access",
  "githubFreeUrl" => "https://github.com/pixinvent",
  "facebookUrl" => "https://www.facebook.com/pixinvents/",
  "twitterUrl" => "https://x.com/pixinvents",
  "githubUrl" => "https://github.com/pixinvent",
  "dribbbleUrl" => "https://dribbble.com/pixinvent",
  "instagramUrl" => "https://www.instagram.com/pixinvents/"
];
